In [10]:
import numpy as np
import scipy.linalg as sal
import math

In [2]:
def inner_product(left_vec, right_vec):
    bra = (np.conj(left_vec)).T
    ket = right_vec
    inner_prod = bra @ ket
    return inner_prod

In [3]:
def norm_column_vec(x):
    # m, n = x.shape
    inner_pro = inner_product(x, x)
    # inner_prodcut is still a 1x1 array, lets extract the element and take its sqrt
    norm = np.sqrt(np.squeeze(inner_pro))
    x_norm = x / norm
    return x_norm

In [4]:
# probability calculation
def probability(left, right):
    left_vec = norm_column_vec(left)
    right_vec = norm_column_vec(right)
    inn_prod = inner_product(left_vec, right_vec)    
    prob = np.square(inn_prod)
    return np.squeeze(prob)

In [56]:
def individual_operators():
    l_2 = np.zeros((6,6))
    s_2 = np.zeros((6,6))
    l_plus = np.zeros((6,6))
    s_plus = np.zeros((6,6))
    
    for i in range(len(l_2[0])):
        for j in range(len(l_2[1])):
            if i==j:
                l_2[i,j] = 2
                s_2[i,j] = 3/4
                
    l_plus[0,1] = math.sqrt(2)
    l_plus[1,2] = math.sqrt(2)
    l_plus[3,4] = math.sqrt(2)
    l_plus[4,5] = math.sqrt(2)
    
    s_plus[0,3] = 1.0
    s_plus[1,4] = 1.0
    s_plus[2,5] = 1.0
    
    l_minus = l_plus.T
    s_minus = s_plus.T
    
    lz = np.array([[1,0,0,0,0,0],[0,0,0,0,0,0],[0,0,-1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,0,0],[0,0,0,0,0,-1]])
    sz = np.array([[1/2,0,0,0,0,0],[0,1/2,0,0,0,0],[0,0,1/2,0,0,0],[0,0,0,-1/2,0,0],[0,0,0,0,-1/2,0],[0,0,0,0,0,-1/2]])
    
    indi_operators = {"l_plus":l_plus,"l_minus":l_minus,"s_plus":s_plus,"s_minus":s_minus,
                    "s_2":s_2,"l_2":l_2,"lz":lz,"sz":sz}
    
    return indi_operators

In [57]:
op = individual_operators()
l_plus= op [ "s_minus"]
l_plus

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [66]:
def product_bases():
    indi_op = individual_operators()
    s_2 = indi_op["s_2"]
    val, vec = sal.eig(s_2)
    
    # product_eigen_vecs are |ml, ms>
    vec1 = vec[0]
    vec2 = vec[1]
    vec3 = vec[2]
    vec4 = vec[3]
    vec5 = vec[4]
    vec6 = vec[5]
    
    function_list = [vec1,vec2,vec3,vec4,vec5,vec6]
    function_dict = {"|1,1/2>":vec1,"|0,1/2>":vec2,"|-1,1/2>":vec3,"|1,-1/2>":vec4,
                    "|0,-1/2>":vec5,"|-1,-1/2>":vec6}
    
    return function_dict

In [67]:
def J_2_operate():
    indi_op = individual_operator()
    l_plus = indi_op["l_plus"]
    l_minus = indi_op["l_minus"]
    s_plus = indi_op["s_plus"]
    s_minus = indi_op["s_minus"]
    l_2 = indi_op["l_2"]
    s_2 = indi_op["s_2"]
    lz = indi_op["lz"]
    sz = indi_op["sz"]
    
    J_2_mat = l_2 + s_2 + l_plus@s_minus + l_minus@s_plus + 2*(lz @ sz)
    
    return J_2_mat

In [68]:
J_2 = J_2_operate()
J_2

array([[3.75      , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 2.75      , 0.        , 1.41421356, 0.        ,
        0.        ],
       [0.        , 0.        , 1.75      , 0.        , 1.41421356,
        0.        ],
       [0.        , 1.41421356, 0.        , 1.75      , 0.        ,
        0.        ],
       [0.        , 0.        , 1.41421356, 0.        , 2.75      ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        3.75      ]])

In [69]:
def coupled_bases():
    J_2 = J_2_operate()
    val, vec = sal.eig(J_2)
    
    return val, vec

In [70]:
coupled_val, coupled_states = coupled_bases()

In [71]:
# we must have J = 3/2 and J = 1/2
# s.t. mj = +-3/2, +-1/2 and mj = +-1/2 respectively, 
# hence, we must get 3.75 for four times and 0.75 two times
coupled_val

array([3.75+0.j, 0.75+0.j, 3.75+0.j, 0.75+0.j, 3.75+0.j, 3.75+0.j])

In [72]:
CG_coeff = coupled_vec.T
CG_coeff

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        , -0.81649658,  0.        ,  0.57735027,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.42640143,  0.        ,  0.90453403,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ]])

In [82]:
prepared_state = CG_coeff[4]
prod_vec = product_bases()
minus_one_half = prod_vec["|-1,1/2>"]
measured_state = minus_one_half

prob = probability(measured_state, prepared_state)
prob

0.18181818181818188